/*
 * 
 * Author: Sithum Nanayakkara
 */
package ChessPanels;

import java.awt.Dimension;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author Sithum Nanayakkara <fhb7119@autuni.ac.nz>
 */
public class BoardPanel extends javax.swing.JPanel {
    
    
    private final static Dimension GAMEBOARD_PANEL_DIMENSION = new Dimension(720,720);
    final List<BoardTiles> tiles;
    //private final BoardTiles boardTiles;
    
    /**
     * Creates new form GamePanel
     */
    public BoardPanel() {
        initComponents();
        this.tiles = new ArrayList<>();
        createPanels();
        this.setSize(GAMEBOARD_PANEL_DIMENSION);
        this.setLocation(0, 0);
        this.validate( );
    }
    
    public void createPanels()
    {
        for (int i=0; i<64; i++)
        {
            final BoardTiles tilePanel = new BoardTiles(this,i);
            this.add(tilePanel);
            this.tiles.add(tilePanel);
        }
        
    } 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        setLayout(new java.awt.GridLayout(8, 8));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
