/*
 * 
 * Author: Sithum Nanayakkara
 */
package ChessPanels;

import ChessLogic.Common.ProcessMove;
import java.awt.Dimension;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author Sithum Nanayakkara <fhb7119@autuni.ac.nz>
 */
public class BoardPanel extends javax.swing.JPanel {
    
    private ProcessMove processMove;
    private final static Dimension GAMEBOARD_PANEL_DIMENSION = new Dimension(720,720);
    final List<BoardTiles> tiles;
    private Integer initialXCoordinate;
    private Integer finalXCoordinate;
    private Integer initialYCoordinate;
    private Integer finalYCoordinate;
    //private final BoardTiles boardTiles;
    
    /**
     * Creates new form GamePanel
     */
    public BoardPanel(GamePanel gamePanel) {
        initComponents();
        this.tiles = new ArrayList<>();
        createPanels();
        this.setSize(GAMEBOARD_PANEL_DIMENSION);
        this.setLocation(0, 0);
        this.validate( );
        this.initialXCoordinate = null;
        this.finalXCoordinate = null;
        this.initialYCoordinate = null;
        this.finalYCoordinate = null;
        this.processMove = new ProcessMove();
    }
    
    public void createPanels()
    {
        for (int c=0; c<8; c++)
        {
            for(int r=0; r<8; r++)
            {
                final BoardTiles tilePanel = new BoardTiles(this,c,r);
                this.add(tilePanel);
                this.tiles.add(tilePanel);
            }
        }
    } 
    
    public Integer getInitialXCoordinate() {
        return initialXCoordinate;
    }

    public void setInitialXCoordinate(Integer initialCoordinate) {
        this.initialXCoordinate = initialCoordinate;
    }

    public Integer getFinalXCoordinate() {
        return finalXCoordinate;
    }

    public void setFinalXCoordinate(Integer finalCoordinate) {
        this.finalXCoordinate = finalCoordinate;
    }
    
    public Integer getInitialYCoordinate() {
        return initialYCoordinate;
    }

    public void setInitialYCoordinate(Integer initialCoordinate) {
        this.initialYCoordinate = initialCoordinate;
    }

    public Integer getFinalYCoordinate() {
        return finalYCoordinate;
    }

    public void setFinalYCoordinate(Integer finalCoordinate) {
        this.finalYCoordinate = finalCoordinate;
    }
    
    public void ProcessMove()
    {
        int returnValue = processMove.getMoveCells(initialXCoordinate, initialYCoordinate,finalXCoordinate, finalYCoordinate);
        if(returnValue != 0)
        {
            this.initialXCoordinate = null;
            this.finalXCoordinate = null;
            this.initialYCoordinate = null;
            this.finalYCoordinate = null;
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(153, 255, 255), new java.awt.Color(0, 51, 51), new java.awt.Color(51, 255, 255)));
        setOpaque(false);
        setLayout(new java.awt.GridLayout(8, 8));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
